---
- name: Install packages
  become: true
  package:
    name: podman
    state: present

- name: Build container images
  block:
    - name: Build logscraper container image - Zuul
      shell: >
        podman build -t quay.io/logscraper:dev -f Dockerfile
      args:
        chdir: "{{ zuul.projects['opendev.org/openstack/ci-log-processing'].src_dir }}"
      when: zuul is defined

    - name: Build logscraper container image - non Zuul
      shell: >
        podman build -t quay.io/logscraper:dev -f Dockerfile
      args:
        chdir: "{{ playbook_dir }}"
      when: zuul is not defined

    - name: Get logscraper image id
      shell: |
        podman images --noheading quay.io/logscraper:dev  | awk '{print $3}'
      register: _logscraper_image_id

    - name: Print all images
      shell: |
        podman images

    - name: Replace container images
      set_fact:
        container_images:
          logscraper: "{{ _logscraper_image_id.stdout }}"
          logsender: "{{ _logscraper_image_id.stdout }}"
