---
- name: Setup Opensearch
  shell: >
    podman run -d --name opensearch \
      --network host \
      -e "discovery.type=single-node" \
      -e "OPENSEARCH_INITIAL_ADMIN_PASSWORD={{ opensearch_pass }}" \
      quay.io/software-factory/opensearch:2.13.0

- name: Wait for Opensearch to be up
  wait_for:
    host: 127.0.0.1
    port: 9200
    delay: 10
    timeout: 300

- name: Wait for Opensearch to be up
  uri:
    url: "https://127.0.0.1:9200"
    user: "{{ opensearch_user }}"
    password: "{{ opensearch_pass }}"
    force_basic_auth: true
    method: GET
    validate_certs: false
    status_code: "200"
  register: result
  until: result.status == 200
  retries: 30
  delay: 10
