---
- name: Build images
  ansible.builtin.include_tasks: build.yml

- name: Configure OpenSearch
  ansible.builtin.include_tasks: opensearch.yml

- name: Configure log processing services
  ansible.builtin.include_tasks: logprocessing.yml

- name: Verify log processing workflow
  ansible.builtin.include_tasks: verify.yml
