---
- project:
    templates:
      - publish-tox-docs-infra
      - publish-to-pypi-quietly
    check: &logcheck
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py38
    gate: *logcheck
