---
- job:
    name: ci-log-processing-functional-test-fedora-34
    description: Test is validating ci log processing services
    run: ansible/playbooks/check-services.yml
    nodeset:
      nodes:
        - name: fedora-34
          label: fedora-34

- project:
    templates:
      - publish-tox-docs-infra
      - publish-to-pypi-quietly
    check: &logcheck
      jobs:
        - openstack-tox-linters
        - openstack-tox-pep8
        - openstack-tox-py38
        - ci-log-processing-functional-test-fedora-34
    gate: *logcheck
