---
- job:
    name: ci-log-processing-functional-test-centos-9-stream-sender
    description: Test is validating Logscraper and logsender services
    run: ansible/playbooks/check-services.yml
    nodeset:
      nodes:
        - name: centos-9-stream
          label: centos-9-stream

# Image building jobs
# NOTE: secret encrypted with opendev/system-config repo
- secret:
    name: cilogprocessing-docker
    data:
      username: cilogprocessing
      password: !encrypted/pkcs1-oaep
        - s8H0t10lkvwZchmd4D0dh1T/OpB6zUIixqL/7S60BARw8DqAH26KhCHpLhAMEfaFUOa85
          Q2Q6HRCt+K4u97oDQ2BihmKHRqosVFUFcx7uVw2LQyLX474r74AOgBZ/VYdqjE+P8G9sT
          w0AUL7RWE8FEg7K8Fj/PQLM9QYTlX2HJdTMCOQUXhOCzduCxWU9zUMbjff9F9YsrZIXsz
          4faTaAOgxG7f/4MvVKsztSjXivE56t9zXz/5kfJMIf2wXrSwjWxdjriOcmbjkxQbzDfz5
          4TGs/1Pg+yZJBmJg0M5FhW+QnYEGzE5nxRW2a+5H8o10qSTMGKDuB+yJmPSDdVrb+G1xQ
          qUMe2YDKZu9ZCxtXp0KUakMAqXGa4tiGFdU3eGHiRZVc1cqDtQn0pAUNZQUky+LtbMea/
          MkVFPyBu3qeQi9MOm1W9YqB7ISf8D0GPiyuqUHzq+AOhScor+DcJqbgRKBkVYdqKVj2U4
          FBgIwU2WdydnNZ/HvK0sZb4MNAWrSuK+T3I5b00OXeA4BfvxLU0BIKOjAwvcYLsVg9fXd
          j76rPq0KZvsD2P7Aih8bDxWc03YdXXefl0LhMXNaUZHamrUEYyQsf5jADo2MUeLA+Iidk
          CnLYa/cR4qcGbhK0XtKjCBvx/Zk6phPF2vvY3tTN7Caknlz4NYq/ggASrxekeg=

- job:
    name: ci-log-processing-build-image
    parent: opendev-build-docker-image
    description: Build logscraper
    allowed-projects: openstack/ci-log-processing
    timeout: 2700
    vars: &cilogprocessing_image_vars
      docker_images:
        - context: .
          repository: cilogprocessing/logscraper
          target: logscraper
          tags:
            &imagetag "{{ zuul.tag is defined | ternary([zuul.get('tag', '').split('.')[0], '.'.join(zuul.get('tag', '').split('.')[:2]), zuul.get('tag', '')], ['latest']) }}"

- job:
    name: ci-log-processing-upload-image
    parent: opendev-upload-docker-image
    description: Build Docker images and upload to Docker Hub.
    allowed-projects: openstack/ci-log-processing
    secrets:
      name: docker_credentials
      secret: cilogprocessing-docker
      pass-to-parent: true
    vars:
      <<: *cilogprocessing_image_vars
      upload_docker_image_promote: false
    dependencies:
      - name: openstack-tox-pep8
        soft: true
      - name: openstack-tox-py312
        soft: true
      - name: ci-log-processing-functional-test-centos-9-stream-sender
        soft: true
      - name: ci-log-processing-build-image
        soft: true

- project:
    templates:
      - publish-tox-docs-infra
      - publish-to-pypi-quietly
    check:
      jobs:
        - openstack-tox-linters
        - openstack-tox-pep8
        - openstack-tox-py312
        - ci-log-processing-build-image
        - ci-log-processing-functional-test-centos-9-stream-sender
    gate:
      jobs:
        - openstack-tox-linters
        - openstack-tox-pep8
        - openstack-tox-py312
        - ci-log-processing-functional-test-centos-9-stream-sender
        - ci-log-processing-build-image
    post:
      jobs:
        - ci-log-processing-build-image
        - ci-log-processing-upload-image
