---
- job:
    name: ci-log-processing-functional-test-centos-8-stream-sender
    description: Test is validating Logscraper and logsender services
    run: ansible/playbooks/check-services-sender.yml
    nodeset:
      nodes:
        - name: centos-8-stream
          label: centos-8-stream

# Image building jobs
# NOTE: secret encrypted with opendev/system-config repo
- secret:
    name: cilogprocessing-docker
    data:
      username: cilogprocessing
      password: !encrypted/pkcs1-oaep
        - HYNNwWxpT2hWhKOb2Mc1jziFEhHl7X7CKq1BR+ep8U81n80VLYfhhsGQNIVRUUOSWwLSy
          zTOyInPdYRYy0sAW1wRllFttdQGulzmgb26R01sjz34/OSttbd2BHKRGCZM8bY7zkWVLN
          ACPOcm12eTceBgGNKYJ/TT17Jub5iwp6lPgtLWbT92QbLBVWbxexZEfT0X95GsRz8S5uo
          jXCpKbzNlDnyOCGkMDWpSKPa3K+r+stkmO7+cMPKIf9nhEB+gblTCfXJysa6hfqx/sEaj
          ovQR6btu1VljorG5VQG47jL2d/AJGQj6B0ibd053+mdjljg5DWoUYOpxdhzvxAZJsvozA
          NYCD0jKsPjEBZf/Lx3QPizLhl/iZUPGQUQgw2Y94ck7R2trcj7y8J4qHiXD2bOrUUmeZv
          31A56Rhx/nWIcP8BD0km9KUBVk/TleG32Bsbz74gvf4yIJ4vpJS/wqyK3v5kuoguym0Nx
          aQRH0L1NZfN4uOQQPuh1tytsnoipl4a5sRgE7X3rZwAI+cX+WaEc613/CvA48lDgSH5SO
          UzGbtzHV3q4RuIiHkdxpwFYzF6vrPBx04UVBnG4uR8nqyK6dP+g5SYIYXNrUHwmkYwM6X
          csDScfIz7yBkms1OOomcb7tqm87R9NHqf8M13SsA3xqTDk+j2yvY634UmSTbuM=

- job:
    name: ci-log-processing-build-image
    parent: opendev-build-docker-image
    description: Build logscraper
    allowed-projects: openstack/ci-log-processing
    timeout: 2700
    vars: &cilogprocessing_image_vars
      docker_images:
        - context: .
          repository: cilogprocessing/logscraper
          target: logscraper
          tags:
            &imagetag "{{ zuul.tag is defined | ternary([zuul.get('tag', '').split('.')[0], '.'.join(zuul.get('tag', '').split('.')[:2]), zuul.get('tag', '')], ['latest']) }}"

- job:
    name: ci-log-processing-upload-image
    parent: opendev-upload-docker-image
    description: Build Docker images and upload to Docker Hub.
    allowed-projects: openstack/ci-log-processing
    secrets:
      name: docker_credentials
      secret: cilogprocessing-docker
      pass-to-parent: true
    vars: *cilogprocessing_image_vars
    dependencies:
      - name: openstack-tox-pep8
        soft: true
      - name: openstack-tox-py38
        soft: true
      - name: ci-log-processing-functional-test-centos-8-stream-sender
        soft: true
      - name: ci-log-processing-build-image
        soft: true

- project:
    templates:
      - publish-tox-docs-infra
      - publish-to-pypi-quietly
    check:
      jobs:
        - openstack-tox-linters
        - openstack-tox-pep8
        - openstack-tox-py38
        - ci-log-processing-build-image
        - ci-log-processing-functional-test-centos-8-stream-sender
    gate:
      jobs:
        - openstack-tox-linters
        - openstack-tox-pep8
        - openstack-tox-py38
        - ci-log-processing-functional-test-centos-8-stream-sender
        - ci-log-processing-build-image
    post:
      jobs:
        - ci-log-processing-build-image
        - ci-log-processing-upload-image
