---
- job:
    name: ci-log-processing-functional-test-centos-9-stream-sender
    description: Test is validating Logscraper and logsender services
    run: ansible/playbooks/check-services.yml
    nodeset:
      nodes:
        - name: centos-9-stream
          label: centos-9-stream

# Image building jobs
# NOTE: secret encrypted with openstack/ci-log-processing repo
- secret:
    name: cilogprocessing-docker
    data:
      username: cilogprocessing
      password: !encrypted/pkcs1-oaep
        - uOZ97UlkimpLofOZD3DK6/mbyjz74khbRFN28p/MQSULiAl8DPGBHGIUwVhdI6U80N4yF
          aCueW74rbAgsKX9po9ze1m7EQ1shmyplhGPLL8mY2WsEmuTEMGLnDdE/XN3jT8oy8NwYj
          9y6FIwKnqtmvOHxkyrnN88nYvY4rYmQ9ycYcXT03i4/eiSpL11EVVE1wmgygqR9y4s5OC
          avpv/ka5gyweRiba51hJnot+x+4x2fbeIuAXUikZmuJXLVIGbPQCweb9OX5zS+b/piVMj
          N11ZiLmJr0i2cy/qMINNVI+D0GBdn3v//4M2MpzI+a5bmK2ETMazTu1mH82Dd4d5Vtu17
          Ai6NoJjqgiJhUiCxq6Kupwu5fDRKShvyH+uPHOkSPEdBBq5Ojt+fRT8ZtVxWwHkZ1UPqA
          fsmIw1eQvyyDK7qshpoOCjerkDtj7DAcxh5zRDWnsY+qPAzvqSEODwh8qr494n1ATsaI8
          40q3Tk+CAdN0zn93lZr21c8MsyNohOnrs1diU2VECL/6zrfTZEUc0C6u8H125qltNsIQ4
          spJnvpvfZcPzYdK8bQ7ntPnpN6hxLMuW9Kwq0FUK4KGs5wiD4Kc4JSQ+LT3XQXFVAD35C
          CMyf7MJOADn1cWw0G+iG40Xn1ODBl7KyWtHaiOA4pbA494ctJ8GP/72X8xXO6Q=

- job:
    name: ci-log-processing-build-image
    parent: opendev-build-docker-image
    description: Build logscraper
    allowed-projects: openstack/ci-log-processing
    timeout: 2700
    vars: &cilogprocessing_image_vars
      docker_images:
        - context: .
          repository: cilogprocessing/logscraper
          target: logscraper
          tags:
            &imagetag "{{ zuul.tag is defined | ternary([zuul.get('tag', '').split('.')[0], '.'.join(zuul.get('tag', '').split('.')[:2]), zuul.get('tag', '')], ['latest']) }}"

- job:
    name: ci-log-processing-upload-image
    parent: opendev-upload-docker-image
    description: Build Docker images and upload to Docker Hub.
    allowed-projects: openstack/ci-log-processing
    secrets:
      name: docker_credentials
      secret: cilogprocessing-docker
      pass-to-parent: true
    vars:
      <<: *cilogprocessing_image_vars
      upload_docker_image_promote: false
    dependencies:
      - name: openstack-tox-pep8
        soft: true
      - name: openstack-tox-py312
        soft: true
      - name: ci-log-processing-functional-test-centos-9-stream-sender
        soft: true
      - name: ci-log-processing-build-image
        soft: true

- project:
    templates:
      - publish-tox-docs-infra
      - publish-to-pypi-quietly
    check:
      jobs:
        - openstack-tox-linters
        - openstack-tox-pep8
        - openstack-tox-py312
        - ci-log-processing-build-image
        - ci-log-processing-functional-test-centos-9-stream-sender
    gate:
      jobs:
        - openstack-tox-linters
        - openstack-tox-pep8
        - openstack-tox-py312
        - ci-log-processing-functional-test-centos-9-stream-sender
        - ci-log-processing-build-image
    post:
      jobs:
        - ci-log-processing-build-image
        - ci-log-processing-upload-image
