---
- job:
    name: ci-log-processing-functional-test-centos-8-stream
    description: Test is validating ci log processing services
    run: ansible/playbooks/check-services.yml
    nodeset:
      nodes:
        - name: centos-8-stream
          label: centos-8-stream
- job:
    name: ci-log-processing-functional-test-centos-8-stream-sender
    description: Test is validating Logscraper and logsender services
    run: ansible/playbooks/check-services-sender.yml
    nodeset:
      nodes:
        - name: centos-8-stream
          label: centos-8-stream

- project:
    templates:
      - publish-tox-docs-infra
      - publish-to-pypi-quietly
    check: &logcheck
      jobs:
        - openstack-tox-linters
        - openstack-tox-pep8
        - openstack-tox-py38
        - ci-log-processing-functional-test-centos-8-stream
        - ci-log-processing-functional-test-centos-8-stream-sender
    gate: *logcheck
