AWSTemplateFormatVersion: "2010-09-09"

Description: ECR repo for Logstash containers

Resources:

  LogstashECRRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "openstack-logstash-repository"

  OpenSearchAdminCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: 'Password for admin account in OpenSearch'
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: 'password'
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

Outputs:

  LogstashECRRepoArn:
    Value: !GetAtt LogstashECRRepo.Arn
    Export:
      Name: LogstashECRRepoArn

  OpenSearchAdminCredentialsSecret:
    Value: !Ref OpenSearchAdminCredentialsSecret
    Export:
      Name: OpenSearchAdminCredentialsSecret
