---
- name: Generate podman-loggearman-{{ item }} script
  template:
    src: loggearman.sh.j2
    dest: "/usr/local/bin/podman-loggearman-{{ item }}"
    mode: '0755'
  notify:
    - restart loggearman {{ item }}

- name: Generate systemd unit loggearman-{{ item }}
  template:
    src: loggearman.service.j2
    dest: "/etc/systemd/system/loggearman-{{ item }}.service"
    owner: root
    group: root
  notify:
    - restart loggearman {{ item }}
