---
logscraper_user: logscraper
logscraper_group: logscraper
logscraper_gid: 10210
logscraper_uid: 10210
logscraper_dir: /etc/logscraper

container_images:
  # FIXME: Create new project on Docker hub that will contain that image
  logscraper: quay.io/software-factory/logscraper:latest

# Example:
# tenant_builds:
#   - tenant: openstack
#     gearman_port: 4731
#     gearman_server: logstash.openstack.org
#     zuul_api_url: https://zuul.opendev.org/api/tenant/openstack
#     insecure: false
#     logscraper_workers: 1
#   - tenant: sometenant
#     zuul_api_url: https://zuul.opendev.org/api/tenant/sometenant
#     insecure: true
#     download: true
#     download_dir: /mnt/logscraper/sometenant
#     file_list: ""
#     job_name:
#       - test
#       - test_new
#     logstash_url: https://somelogstash.com:9999
#     max_skipped: 100
#     debug: true
#     logscraper_wait_time: 120
#     custom_ca_crt: ""
tenant_builds: []
