---
logscraper_user: logscraper
logscraper_group: logscraper
logscraper_gid: 10210
logscraper_uid: 10210
logscraper_dir: /etc/logscraper

container_images:
  # FIXME: Create new project on Docker hub that will contain that image
  logscraper: quay.rdoproject.org/software-factory/logscraper:latest

# Example:
# tenant_builds:
#   - tenant: openstack
#     gearman_port: 4731
#     gearman_server: logstash.openstack.org
#     zuul_api_url: https://zuul.opendev.org/api/tenant/openstack
#     insecure: False
#   - tenant: sometenant
#     gearman_port: 4731
#     gearman_server: logstash.openstack.org
#     zuul_api_url: https://zuul.opendev.org/api/tenant/sometenant
#     insecure: True
tenant_builds: []
