---
- name: Create dedicated group
  group:
    name: "{{ logscraper_group }}"
    gid: "{{ logscraper_gid }}"
    state: present

- name: Create dedicated user
  user:
    name: "{{ logscraper_user }}"
    state: present
    comment: "Dedicated user for logscraper"
    group: "{{ logscraper_group }}"
    uid: "{{ logscraper_uid }}"
    shell: "/sbin/nologin"
    create_home: false

- name: Create dedicated directory
  file:
    path: "{{ logscraper_dir }}"
    state: directory
    owner: "{{ logscraper_user }}"
    group: "{{ logscraper_group }}"
    mode: "0755"

- name: Copy logscraper config file
  template:
    src: config.yaml.j2
    dest: "{{ logscraper_dir }}/config.yaml"
    owner: "{{ logscraper_user }}"
    group: "{{ logscraper_group }}"
    mode: "0640"

- name: Ensure container software is installed
  package:
    name: podman
    state: present

- name: Configure logscraper service
  include_tasks: service.yml
  loop: "{{ tenant_builds }}"
