---
- hosts: all
  become: true
  vars:
    # loggearman - worker
    output_host: 0.0.0.0
    output_port: 9999
    gearman_host: 0.0.0.0
    gearman_port: 4730
    log_cert_verify: false
    # loggearman - client
    source_url: ""
    gearman_client_host: "{{ gearman_host }}"
    gearman_client_port: "{{ gearman_port }}"
    # logscraper
    tenant_builds:
      - tenant: openstack
        gearman_port: "{{ gearman_port }}"
        gearman_server: "{{ gearman_host }}"
        zuul_api_url:
          - https://zuul.opendev.org/api/tenant/openstack
        insecure: false
        job_names: []
        download: false
  pre_tasks:
    - name: Update all packages
      become: true
      package:
        name: "*"
        state: latest
  roles:
    - check-services
    - backup-dashboards-objects
