---
- name: Generate logsender script
  template:
    src: logsender.sh.j2
    dest: "/usr/local/bin/logsender-{{ item.tenant }}"
    mode: '0755'
  register: _start_script

- name: Generate systemd unit
  template:
    src: logsender.service.j2
    dest: "/etc/systemd/system/logsender-{{ item.tenant }}.service"
    owner: root
    group: root

- name: Enable and restart service
  service:
    name: logsender-{{ item.tenant }}
    state: restarted
    daemon-reload: true
    enabled: true
  when: _start_script.changed

- name: Ensure that service is running
  service:
    name: logsender-{{ item.tenant }}
    state: started
    daemon-reload: true
    enabled: true
